apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: hellok8s
  labels:
    app: hellok8s
spec:
  containers:
  - name: hellok8s-container
    image: rmaubrey2018/rubytest:v2
---

apiVersion: v1
kind: Pod
metadata:
  namespace: my-namespace
  name: hellok8s
  labels:
    app: hellok8s
spec:
  containers:
  - name: hellok8s-container
    image: rmaubrey2018/rubytest:v4
