apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: echo-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: echo
            image: busybox
            command: ["echo", "Triggered by a CronJob"]
